# Import libraries
library('nlme')
library('reshape2')
library('emmeans')
library('dplyr')
# Load amygdala volumes generated by clean_data.py
data <- read.csv('~/Downloads/melted.csv')
dat <- data %>% filter(Region != 'Whole_amygdala')
dat_filter <- data %>% filter(Region == 'Whole_amygdala')
# Set up the parameters of the linear mixed effects model for 9 subnuclei
m <- lme(Volume ~Condition*Region+Age+Sex+scale(ICV), 
         random =~ 1|Site/Subject, data=dat, method="REML")
# Set up the parameters of the linear mixed effects model for whole amygdala
n <- lme(Volume ~Condition+Age+Sex+scale(ICV), 
         random =~ 1|Site/Subject, data=dat_filter, method="REML")
summary(m)
summary(n)
# Get p-values of the model
anova.lme(m, type = "marginal", adjustSigma = F)
anova.lme(n, type = "marginal", adjustSigma = F)
# Get estimated marginal means of the model and save in a text file (subnuclei)
e<-emmeans(m, pairwise ~ Condition|Region, adjust= "none")
edf4 <- as.data.frame(e$contrasts)
edf4$fdr.adj.p <- p.adjust(edf4$p.value, method ="fdr")
write.csv(edf4, '~/Downloads/estimated_marginal_means_subnuclei.csv')
# Get estimated marginal means of the model and save in a text file (whole amygdala)
f<-emmeans(n, pairwise ~ Condition, adjust= "none")
fdf4 <- as.data.frame(f$contrasts)
fdf4$fdr.adj.p <- p.adjust(fdf4$p.value, method ="fdr")
write.csv(fdf4, '~/Downloads/estimated_marginal_means_wholeamygdala.csv')
# Alter format for general linear model
wide <- dcast(dat, Subject + Condition + Sex + Age + Site + ICV ~ Region, value.var="Volume")
names(wide) <- gsub( '-', '_',names(wide))
# General linear model on two largest amygdala subnuclei
m2 <- lm(Lateral_nucleus ~ Condition + Sex + Age + Site + ICV, data=wide)
m3 <- lm(Basal_nucleus ~ Condition + Sex + Age + Site + ICV, data=wide)
summary(m2)
summary(m3)
# Power test for small-to-medium effects in general linear model
pwr::pwr.f2.test(u = 4, v = 178 - 2 - 1, f2 = 0.03/(1 - 0.03), sig.level = 0.05)