# Import libraries
library('nlme')
library('reshape2')
library('emmeans')
# Load amygdala volumes generated by clean_data.py
dat <- read.csv('/media/lauri/heinrich/My_Computer/Documents/sync_me/AMY-HCP/reports/melted.csv') 
# Set up the parameters of the linear mixed effects model
m <- lme(Volume ~Condition*Region+Age+Sex+scale(ICV), 
         random =~ 1|Site/Subject, data=dat, method="REML")
summary(m)
# Get p-values of the model
anova.lme(m, type = "marginal", adjustSigma = F)
# Get estimated marginal means of the model and save in a text file
e<-emmeans(m, pairwise ~ Condition|Region, adjust= "none")
edf4 <- as.data.frame(e$contrasts)
edf4$fdr.adj.p <- p.adjust(edf4$p.value, method ="fdr")
write.csv(edf4, '/home/lauri/Downloads/estimated_marginal_means.csv')
# Alter format for general linear model
wide <- dcast(dat, Subject + Condition + Sex + Age + Site + ICV ~ Region, value.var="Volume")
names(wide) <- gsub( '-', '_',names(wide))
# General linear model on two largest amygdala subnuclei
m2 <- lm(Lateral_nucleus ~ Condition + Sex + Age + Site + ICV, data=wide)
m3 <- lm(Basal_nucleus ~ Condition + Sex + Age + Site + ICV, data=wide)
summary(m2)
summary(m3)
# Power test for small-to-medium effects in general linear model
pwr::pwr.f2.test(u = 4, v = 178 - 2 - 1, f2 = 0.03/(1 - 0.03), sig.level = 0.05)